core.home:
  path: /
  defaults:
    _controller: "core.userController:indexAction"

core.all:
    path: /all
    defaults:
      _controller: "core.userController:showAction"

core.fullProfile:
    path: /full/{$id}
    defaults:
      _controller: "core.userController:getUserProfileComplete"

core.UserByID:
      path: /user/{id}
      defaults:
        _controller: "core.userController:getUserProfileComplete"


