<?php

namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\APCPaymentRepositoryInterface;
/**
 * APCPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APCPaymentRepository extends EntityRepository implements APCPaymentRepositoryInterface
{
}
