<?php

namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ArtisticExhibitionRepositoryInterface;
/**
 * ArtisticExhibitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisticExhibitionRepository extends EntityRepository implements ArtisticExhibitionRepositoryInterface
{
}
