<?php


    namespace CoreBundle\Repository;
    use Doctrine\ORM\EntityRepository;
    use CoreDomain\Objects\AudioRecordingRepositoryInterface;
    

/**
 * AudioRecordingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioRecordingRepository extends EntityRepository implements AudioRecordingRepositoryInterface
{
}
