<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\AwardRepositoryInterface;
    

/**
 * AwardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwardRepository extends EntityRepository implements AwardRepositoryInterface
{
}
