<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\BookChapterRepositoryInterface;
    

/**
 * BookChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookChapterRepository extends EntityRepository implements BookChapterRepositoryInterface
{
}
