<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\BookReviewRepositoryInterface;
    

/**
 * BookReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookReviewRepository extends EntityRepository implements BookReviewRepositoryInterface
{
}
