<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\BroadcastInterviewRepositoryInterface;
    

/**
 * BroadcastInterviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BroadcastInterviewRepository extends EntityRepository implements BroadcastInterviewRepositoryInterface
{
}
