<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\CareerStatusRepositoryInterface;
    

/**
 * CareerStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareerStatusRepository extends EntityRepository implements CareerStatusRepositoryInterface
{
}
