<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\CashFunderRepositoryInterface;
    

/**
 * CashFunderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashFunderRepository extends EntityRepository implements CashFunderRepositoryInterface
{
}
