<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ChoreographyRepositoryInterface;
    

/**
 * ChoreographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoreographyRepository extends EntityRepository implements ChoreographyRepositoryInterface
{
}
