<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\CitizenshipRepositoryInterface;
    

/**
 * CitizenshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitizenshipRepository extends EntityRepository implements CitizenshipRepositoryInterface
{
}
