<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\CommunityServiceRepositoryInterface;
    

/**
 * CommunityServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityServiceRepository extends EntityRepository implements CommunityServiceRepositoryInterface
{
}
