<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\CommitteeMembershipRepositoryInterface;
    

/**
 * CommitteeMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitteeMembershipRepository extends EntityRepository implements CommitteeMembershipRepositoryInterface
{
}
