<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ConferencePosterRepositoryInterface;
    

/**
 * ConferencePosterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferencePosterRepository extends EntityRepository implements ConferencePosterRepositoryInterface
{
}
