<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ConferenceReviewingRefereeingRepositoryInterface;
    

/**
 * ConferenceReviewingRefereeingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceReviewingRefereeingRepository extends EntityRepository implements ConferenceReviewingRefereeingRepositoryInterface
{
}
