<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ConferencePaperRepositoryInterface;
    

/**
 * ConferencePaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferencePaperRepository extends EntityRepository implements ConferencePaperRepositoryInterface
{
}
