<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ConferenceAbstractRepositoryInterface;
    

/**
 * ConferenceAbstractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceAbstractRepository extends EntityRepository implements ConferenceAbstractRepositoryInterface
{
}
