<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ConsultingAdvisoryRepositoryInterface;
    

/**
 * ConsultingAdvisoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultingAdvisoryRepository extends EntityRepository implements ConsultingAdvisoryRepositoryInterface
{
}
