<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\CourseDevelopedRepositoryInterface;
    

/**
 * CourseDevelopedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseDevelopedRepository extends EntityRepository implements CourseDevelopedRepositoryInterface
{
}
