<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\CourseTaughtRepositoryInterface;
    

/**
 * CourseTaughtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseTaughtRepository extends EntityRepository implements CourseTaughtRepositoryInterface
{
}
