<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\CuratorialMuseumExhibitionRepositoryInterface;
    

/**
 * CuratorialMuseumExhibitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuratorialMuseumExhibitionRepository extends EntityRepository implements CuratorialMuseumExhibitionRepositoryInterface
{
}
