<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\DataSetRepositoryInterface;
    

/**
 * DataSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSetRepository extends EntityRepository implements DataSetRepositoryInterface
{
}
