<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\DegreeRepositoryInterface;
    

/**
 * DegreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DegreeRepository extends EntityRepository implements DegreeRepositoryInterface
{
}
