<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\DictionaryEntryRepositoryInterface;
    

/**
 * DictionaryEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryEntryRepository extends EntityRepository implements DictionaryEntryRepositoryInterface
{
}
