<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\DisclosureRepositoryInterface;
    

/**
 * DisclosureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisclosureRepository extends EntityRepository implements DisclosureRepositoryInterface
{
}
