<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\DissertationRepositoryInterface;
    

/**
 * DissertationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DissertationRepository extends EntityRepository implements DissertationRepositoryInterface
{
}
