<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\DistinctionRepositoryInterface;
    

/**
 * DistinctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistinctionRepository extends EntityRepository implements DistinctionRepositoryInterface
{
}
