<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\EditedBookRepositoryInterface;
    

/**
 * EditedBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditedBookRepository extends EntityRepository implements EditedBookRepositoryInterface
{
}
