<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\EmployeeSupervisionRepositoryInterface;
    

/**
 * EmployeeSupervisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeSupervisionRepository extends EntityRepository implements EmployeeSupervisionRepositoryInterface
{
}
