<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\EventAdministrationRepositoryInterface;
    

/**
 * EventAdministrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAdministrationRepository extends EntityRepository implements EventAdministrationRepositoryInterface
{
}
