<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ExhibitionCatalogueRepositoryInterface;
    

/**
 * ExhibitionCatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExhibitionCatalogueRepository extends EntityRepository implements ExhibitionCatalogueRepositoryInterface
{
}
