<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\GraduateExaminationRepositoryInterface;
    

/**
 * GraduateExaminationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraduateExaminationRepository extends EntityRepository implements GraduateExaminationRepositoryInterface
{
}
