<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\GrantRepositoryInterface;
    

/**
 * GrantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrantRepository extends EntityRepository implements GrantRepositoryInterface
{
}
