<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\HEInstitutionEmploymentRepositoryInterface;
    

/**
 * HEInstitutionEmploymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HEInstitutionEmploymentRepository extends EntityRepository implements HEInstitutionEmploymentRepositoryInterface
{
}
