<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\InkindFundingRepositoryInterface;
    

/**
 * InkindFundingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InkindFundingRepository extends EntityRepository implements InkindFundingRepositoryInterface
{
}
