<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\InternalOACostApplicationRepositoryInterface;
    

/**
 * InternalOACostApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternalOACostApplicationRepository extends EntityRepository implements InternalOACostApplicationRepositoryInterface
{
}
