<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\JournalIssueRepositoryInterface;
    

/**
 * JournalIssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalIssueRepository extends EntityRepository implements JournalIssueRepositoryInterface
{
}
