<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\JournalReviewingRefereeingRepositoryInterface;
    

/**
 * JournalReviewingRefereeingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalReviewingRefereeingRepository extends EntityRepository implements JournalReviewingRefereeingRepositoryInterface
{
}
