<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\JournalArticleRepositoryInterface;
    

/**
 * JournalArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalArticleRepository extends EntityRepository implements JournalArticleRepositoryInterface
{
}
