<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\LanguageCompetencyRepositoryInterface;
    

/**
 * LanguageCompetencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageCompetencyRepository extends EntityRepository implements LanguageCompetencyRepositoryInterface
{
}
