<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\LicenseRepositoryInterface;
    

/**
 * LicenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseRepository extends EntityRepository implements LicenseRepositoryInterface
{
}
