<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\LightDesignRepositoryInterface;
    

/**
 * LightDesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LightDesignRepository extends EntityRepository implements LightDesignRepositoryInterface
{
}
