<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\LitigationRepositoryInterface;
    

/**
 * LitigationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LitigationRepository extends EntityRepository implements LitigationRepositoryInterface
{
}
