<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\MailingAddressRepositoryInterface;
    

/**
 * MailingAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailingAddressRepository extends EntityRepository implements MailingAddressRepositoryInterface
{
}
