<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ManualRepositoryInterface;
    

/**
 * ManualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManualRepository extends EntityRepository implements ManualRepositoryInterface
{
}
