<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\MentoringRepositoryInterface;
    

/**
 * MentoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentoringRepository extends EntityRepository implements MentoringRepositoryInterface
{
}
