<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\MusicalCompositionRepositoryInterface;
    

/**
 * MusicalCompositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicalCompositionRepository extends EntityRepository implements MusicalCompositionRepositoryInterface
{
}
