<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\MusicalPerformanceRepositoryInterface;
    

/**
 * MusicalPerformanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicalPerformanceRepository extends EntityRepository implements MusicalPerformanceRepositoryInterface
{
}
