<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\NewspaperArticleRepositoryInterface;
    

/**
 * NewspaperArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewspaperArticleRepository extends EntityRepository implements NewspaperArticleRepositoryInterface
{
}
