<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\NonHEEmploymentRepositoryInterface;
    

/**
 * NonHEEmploymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NonHEEmploymentRepository extends EntityRepository implements NonHEEmploymentRepositoryInterface
{
}
