<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\OfficeHeldRepositoryInterface;
    

/**
 * OfficeHeldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeHeldRepository extends EntityRepository implements OfficeHeldRepositoryInterface
{
}
