<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\OnlineResourceRepositoryInterface;
    

/**
 * OnlineResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnlineResourceRepository extends EntityRepository implements OnlineResourceRepositoryInterface
{
}
