<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\OtherStudyRepositoryInterface;
    

/**
 * OtherStudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherStudyRepository extends EntityRepository implements OtherStudyRepositoryInterface
{
}
