<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\PatentRepositoryInterface;
    

/**
 * PatentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatentRepository extends EntityRepository implements PatentRepositoryInterface
{
}
