<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\PerformanceArtRepositoryInterface;
    

/**
 * PerformanceArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformanceArtRepository extends EntityRepository implements PerformanceArtRepositoryInterface
{
}
