<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\PersonInfoRepositoryInterface;
    

/**
 * PersonInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonInfoRepository extends EntityRepository implements PersonInfoRepositoryInterface
{
}
