<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\PersonalLeaveofAbsenceRepositoryInterface;
    

/**
 * PersonalLeaveofAbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalLeaveofAbsenceRepository extends EntityRepository implements PersonalLeaveofAbsenceRepositoryInterface
{
}
