<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ProfessionalDesignationRepositoryInterface;
    

/**
 * ProfessionalDesignationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalDesignationRepository extends EntityRepository implements ProfessionalDesignationRepositoryInterface
{
}
