<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ProfessionalLeaveofAbsenceRepositoryInterface;
    

/**
 * ProfessionalLeaveofAbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalLeaveofAbsenceRepository extends EntityRepository implements ProfessionalLeaveofAbsenceRepositoryInterface
{
}
