<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ProgramDevelopedRepositoryInterface;
    

/**
 * ProgramDevelopedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramDevelopedRepository extends EntityRepository implements ProgramDevelopedRepositoryInterface
{
}
