<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ProjectBudgetRepositoryInterface;
    

/**
 * ProjectBudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectBudgetRepository extends EntityRepository implements ProjectBudgetRepositoryInterface
{
}
