<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ProjectHQPTrainingRepositoryInterface;
    

/**
 * ProjectHQPTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectHQPTrainingRepository extends EntityRepository implements ProjectHQPTrainingRepositoryInterface
{
}
