<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ProjectParticipantRepositoryInterface;
    

/**
 * ProjectParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectParticipantRepository extends EntityRepository implements ProjectParticipantRepositoryInterface
{
}
