<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ProjectInfoRepositoryInterface;
    

/**
 * ProjectInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectInfoRepository extends EntityRepository implements ProjectInfoRepositoryInterface
{
}
