<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ProjectRiskRepositoryInterface;
    

/**
 * ProjectRiskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRiskRepository extends EntityRepository implements ProjectRiskRepositoryInterface
{
}
