<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ProjectMilestoneRepositoryInterface;
    

/**
 * ProjectMilestoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectMilestoneRepository extends EntityRepository implements ProjectMilestoneRepositoryInterface
{
}
