<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\PromotionTenureAssessmentRepositoryInterface;
    

/**
 * PromotionTenureAssessmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionTenureAssessmentRepository extends EntityRepository implements PromotionTenureAssessmentRepositoryInterface
{
}
