<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\RadioTVProgramRepositoryInterface;
    

/**
 * RadioTVProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadioTVProgramRepository extends EntityRepository implements RadioTVProgramRepositoryInterface
{
}
