<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\RegisteredCopyrightRepositoryInterface;
    

/**
 * RegisteredCopyrightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisteredCopyrightRepository extends EntityRepository implements RegisteredCopyrightRepositoryInterface
{
}
