<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ResearchLocationRepositoryInterface;
    

/**
 * ResearchLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResearchLocationRepository extends EntityRepository implements ResearchLocationRepositoryInterface
{
}
