<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ResearchDatasetRepositoryInterface;
    

/**
 * ResearchDatasetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResearchDatasetRepository extends EntityRepository implements ResearchDatasetRepositoryInterface
{
}
