<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ResearchToolRepositoryInterface;
    

/**
 * ResearchToolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResearchToolRepository extends EntityRepository implements ResearchToolRepositoryInterface
{
}
