<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ReviewSubjectRepositoryInterface;
    

/**
 * ReviewSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewSubjectRepository extends EntityRepository implements ReviewSubjectRepositoryInterface
{
}
