<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ReviewerSuggestionRepositoryInterface;
    

/**
 * ReviewerSuggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewerSuggestionRepository extends EntityRepository implements ReviewerSuggestionRepositoryInterface
{
}
