<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\SetDesignRepositoryInterface;
    

/**
 * SetDesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetDesignRepository extends EntityRepository implements SetDesignRepositoryInterface
{
}
