<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\ShortFictionRepositoryInterface;
    

/**
 * ShortFictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortFictionRepository extends EntityRepository implements ShortFictionRepositoryInterface
{
}
