<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\SpinOffCompanyRepositoryInterface;
    

/**
 * SpinOffCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpinOffCompanyRepository extends EntityRepository implements SpinOffCompanyRepositoryInterface
{
}
