<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\StandardorPolicyRepositoryInterface;
    

/**
 * StandardorPolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandardorPolicyRepository extends EntityRepository implements StandardorPolicyRepositoryInterface
{
}
