<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\SupervisedStudentPublicationRepositoryInterface;
    

/**
 * SupervisedStudentPublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupervisedStudentPublicationRepository extends EntityRepository implements SupervisedStudentPublicationRepositoryInterface
{
}
