<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\TeamCapacityRepositoryInterface;
    

/**
 * TeamCapacityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamCapacityRepository extends EntityRepository implements TeamCapacityRepositoryInterface
{
}
