<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\TextInterviewRepositoryInterface;
    

/**
 * TextInterviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextInterviewRepository extends EntityRepository implements TextInterviewRepositoryInterface
{
}
