<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\TheatricRepositoryInterface;
    

/**
 * TheatricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TheatricRepository extends EntityRepository implements TheatricRepositoryInterface
{
}
