<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\TrademarkRepositoryInterface;
    

/**
 * TrademarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrademarkRepository extends EntityRepository implements TrademarkRepositoryInterface
{
}
