<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

use CoreDomain\User\UserRepositoryInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserRepositoryInterface
{

    private $em;

    /**
     * UserRepository constructor.
     *
     * @param \Doctrine\ORM\EntityManager         $em
     * @param \Doctrine\ORM\Mapping\ClassMetadata $class
     */
    public function __construct(EntityManager $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->em = $em;
    }

    /**
     * {@inheritdoc}
     */
    public function getAll()
    {
        return parent::findAll();
    }

    /**
     * @param $id
     *
     * @return null|object
     */
    public function getUserById($id)
    {
        return parent::find($id);
    }

    /**
     * @param $id
     */
    public function getUserPersonalInformation($id)
    {
        $query = $this->em->createQuery('SELECT p FROM CoreBundle\Entity\PersonInfo p  where p.userId = :userid');
        $query->setParameter('userid',1);
        $users = $query->getResult();
        return $users;
    }
}
