<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\VideoRecordingRepositoryInterface;
    

/**
 * VideoRecordingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRecordingRepository extends EntityRepository implements VideoRecordingRepositoryInterface
{
}
