<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\VisualArtworkRepositoryInterface;
    

/**
 * VisualArtworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisualArtworkRepository extends EntityRepository implements VisualArtworkRepositoryInterface
{
}
