<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\WebAddressRepositoryInterface;
    

/**
 * WebAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebAddressRepository extends EntityRepository implements WebAddressRepositoryInterface
{
}
