<?php


namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use CoreDomain\Objects\WorkingPaperRepositoryInterface;
    

/**
 * WorkingPaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkingPaperRepository extends EntityRepository implements WorkingPaperRepositoryInterface
{
}
